spring:
  datasource:
    url: jdbc:mysql://localhost:3306/A2P?serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379

jwt:
  ACCESS_SECRET_KEY: aidhgjarisdafjskljklriaonsdikrnsnnfkdsijkevklasdfujiielarlfnkanvdkvcxfsdgweasdv
  REFRESH_SECRET_KEY: zsxdfbnjmsdcyuhjkkrtfweecvrdftfvghfgbhmukhtgugwqesfteyhoikdwduigkwgrsdugafjixf

mybatis:
  mapper-locations: classpath*:com/A2P/dev/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true